server:
  port: 3000

spring:
  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:mysql://localhost:3306/caruser?createDatabaseIfNotExist=true
    username: root
    password: ccdccd
    show_sql: true
    driver-class-name: com.mysql.cj.jdbc.Driver
